### ISSUE TITLE
Suggestion: education packages

### ISSUE THREAD

**Issue by gregharvey** [fedy/fedy#570]
Hi,

I am an avid Fedy user and love what you've done with it! I was wondering - off the back of this tweet: https://twitter.com/greg_harvey/status/951438540772134913 - if you would be interested in incorporating an "Education" section with the most popular kids packages within, stuff like Scratch, some drawing software, the kind of thing that ships with edu-focused distros like Ubermix.

Totally understand if you say "No" on the basis it's outside the stated goal of the Fedy project - to bring in software that is *not approved* by the main project.

Thanks,

Greg

**Comment by bddenhartog** [comment]
This would be something I would consider. I'm in the process of planning out a major overhaul to the Fedy ecosystem, and part of that involves shuffling around the "plugins" we offer - making them proper packages, enabling things like package groups and better distribution. I personally see the Fedy of the future being a whole lot easier to use, contribute to, and maintain. I've been using Arch Linux for the past year and a half or so, and really like how the AUR works (user-maintained packages) - I'd like for Fedy to grow and be able to serve multiple distributions, and something in the middle of where we're at currently and the AUR might be a good direction for Fedy to head.

An interesting note on Scratch in particular... it looks like it used to exist in the F19 repositories, but had since been removed. Last updated in 2013, Matthew Miller [wrote a proposal][0] to add Scratch back into the official repositories, but abandoned it due to upstream incompatibilities on 64-bit systems. I wonder how this has changed (I'm unfamiliar with the software or its maintainers).

[0]: https://fedoraproject.org/wiki/Features/Scratch

**Comment by gregharvey** [comment]
Oh, that's good news, nice! I'll keep an eye on this. If you need a tester, I can provide a 10-year-old.
