### ISSUE TITLE
No more mirror to try

### ISSUE THREAD

**Issue by metabsd** [fedy/fedy#585]
Hi,
I try to dnf update my fedora box this morning and I got and error on fedy-release package.

```bash
[myuser@mybox ~] $ sudo dnf update -y
Last metadata expiration check: 0:02:44 ago on Mon 30 Apr 2018 11:34:48 AM EDT.
Dependencies resolved.
=================================================================================================================================================================================================================================================================================
 Package                                                            Arch                                                         Version                                                               Repository                                                           Size
=================================================================================================================================================================================================================================================================================
Installing dependencies:
 fedy-release                                                       noarch                                                       5.0.1-1.fc27                                                          folkswithhats                                                       7.9 k
     replacing  folkswithhats-release.noarch 4.0.0-0

Transaction Summary
=================================================================================================================================================================================================================================================================================
Install  1 Package

Total download size: 7.9 k
Installed size: 125  
Downloading Packages:
[MIRROR] fedy-release.rpm: Interrupted by header callback: Server reports Content-Length: 8096 but expected size is: 8092                                                                                                                                                       
[FAILED] fedy-release.rpm: No more mirrors to try - All mirrors were already tried without success                                                                                                                                                                              

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download RPMS/fedy-release.rpm: All mirrors were tried
```

```bash
cat /etc/redhat-release
Fedora release 27 (Twenty Seven)
```
```bash
[myuser@mybox ~] $ sudo dnf clean packages
0 files removed
```

I retry `dnf update -y` and I got the same error.

I also get Access Denied when I try `https://dl.folkswithhats.org/fedora/`

**Comment by sudoforge** [comment]
As for your error - your local cache is outdated. Users who encounter this same issue should execute:

```
$ dnf clean expire-cache
$ dnf update
```

Note that the above `dnf clean expire-cache` command will expire the cache for all of your repositories. Since this issue should only apply to those that have `folkswithhats-release-4.6.0` or less installed, you can limit the cache expiration to just the repository you have installed on your system:

```
$ dnf clean expire-cache --repo folkswithhats
$ dnf update
```

Users with any version `fedy-release` should not encounter this error.

> I also get Access Denied when I try https://dl.folkswithhats.org/fedora/

This is expected. The repository is hosted on AWS S3 in a private bucket, to which the global CDN (AWS CloudFront) has access.

This is done primarily for cost reasons. When I first took over the project, there was a huge growth in requests - capping at about 5,000,000 requests to the repositories per month, averaging a little less than that today. I pay for Fedy's infrastructure without any assistance, and it is much cheaper to server that sort of volume through CloudFront. Allowing public reads on the S3 bucket would incur costs for listing the files, and an additional cost if users decided to download them.

**Comment by sudoforge** [comment]
Are you _sure_ you successfully cleared your cache? I'm not able to recreate your error.

**Please run the following commands in succession:**

```
$ touch /tmp/fedy.log
$ sudo dnf info folkswithhats-release fedy-release | tee -a /tmp/fedy.log
$ sudo dnf clean expire-cache --repo folkswithhats | tee -a /tmp/fedy.log
$ sudo dnf upgrade -y folkswithhats-release | tee -a /tmp/fedy.log
$ cat /tmp/fedy.log | xclip -selection c
```

The last command will copy the contents of the log file to your clipboard. Please paste it in a new comment on this thread.

**Comment by metabsd** [comment]
I retry this morning and it's working.

**Comment by sudoforge** [comment]
It seems like perhaps your cache didn't get cleared the other day, then. Glad it's working for you!
