### ISSUE TITLE
for Fedora 30 

### ISSUE THREAD

**Issue by krhlnx** [fedy/fedy#651]
Hi

Please release Fedy for Fedora 30...

**Comment by JavascriptMike** [comment]
Good Afternoon from the Appalachian Mountains! 
The land where we make great moonshine and great code fixes!

From a clean Fedora 30 install,  This is what you will need to type in to get it to work.

I went to the website,  https://www.folkswithhats.org/  on the front of the webpage,  There are 3 lines of code.  Run all 3 of them in the terminal
so do this.
Type in 
**su -**
and then your password.   Now you will be logged in root for this exercise.
These are the three lines off the main page.

**dnf install https://dl.folkswithhats.org/fedora/$(rpm -E %fedora)/RPMS/fedy-release.rpm**

**dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm**

**dnf install fedy**

Now copy and paste those three lines of code in.   Yes I know well and understand that some of it will error out.  Thats okay,   Because some of it will not.   We need all of it it done,  because the fix will only fix the part that errored out.

Now,  This is the fedy installer for Fedora 29.   I have used it twice for Fedora 30 without any issues.  
Here is the link for it.

**dnf install https://github.com/fedy/fedy/releases/download/v4.6.1/fedy-4.6.1-1.fc29.noarch.rpm**

AFTER THE COMMAND RUNS and you click Y and it fully installs,   and it comes back to command prompt,   CLOSE THE TERMINAL WINDOW.   

Then go to the start menu and type in fedy or find it under the menu under "APPLICATIONS" -->  "UTILITIES" --> "FEDY"    Select it from the menu to install what you need.  

Lemmie know if you guys want me to upload a picture of my Moonshine still!  Its pretty cool lookin'! 
Heading back up in the mountains,   See you all later.  Have fun!

**Comment by sudoforge** [comment]
@JavascriptMike I've deleted your comment to avoid confusing new and existing users. A release will be made for F30 tonight.

**Comment by JavascriptMike** [comment]
Its rude to delete someones comment when they worked hard on solving the problem and took the time to post a result that works.  
So are you the one developer left who is supposed to be working on the project to update it?

**Comment by sudoforge** [comment]
> Its rude to delete someones comment when they worked hard on solving the problem and took the time to post a result that works.

I empathize with you. I appreciate the detailed comment, however, recommending that users run commands that will most definitely error, and subsequently recommend installing an outdated release, are not instructions that I would want other users following. I recognize that the intentions were good, and I definitely didn't mean to offend you by removing the comment.

> So are you the one developer left who is supposed to be working on the project to update it?

That seems to be me and @danstewart, although with the current workflow, I am the sole developer capable of deploying to our production environment.

> I am curious about your credibility in you claim. I have been disappointed in the F29 development for the past 6 months on Fedy, Somehow after all that foot dragging that has been going on, I dont see a fire under anyones ass all of a sudden for F30.

I understand your frustration - it certainly has made things difficult for users to not be able to install Fedy from the repository for the past release. Unfortunately, life has gotten in the way, and I have been working extremely long hours with little time to dedicate to a project which is kept alive solely out of my interest in making life easier for Linux users.

This is something I hope to change, and I have efforts well underway for automating this process to ease the deployment of new versions, so rest assured that we shouldn't see the same delay in the future.

> What is your source and how do you know tonight?

Me. I am the source, and I know because I am going to release it tonight.

**Comment by eyal0803** [comment]
Hi @sudoforge. Did the release for F30 happen?

**Comment by JavascriptMike** [comment]
Lets wait and give him a week or so to make "the release will be made for F30 tonight."  actually happen.   Its more than fair.    
Its only been 4 days now,   A single programmer can run on coffee for about a week without food or water or sunlight.  
After that we can pretty confidently proclaim him most likely dead from Folgers overdose.   ;)

**Comment by shrimpster00** [comment]
Hey, let's keep things civil here. Come on.

Thanks for your commitment to this project @sudoforge. I've been a Fedy user for years, and I am so glad for this tool. You're doing great and you're appreciated.
When life gets in the way, it gets in the way, and I'm sure we can all understand that. Don't forget that you are more important than this project.

**Comment by OuTopos** [comment]
@sudoforge Thank you for all your work with Fedy. Without it Fedora is crippled in my opinion.

I have total understanding that you have other priorities in life and no one here has the right to demand anything of you.

However, would it be possible to involve more people so releasing fedy would not only depend on one person. My guess is that a lot of people would be willing to help ;)

Again, thank you and I hope to be installing Fedy in future Fedora installs.

***Disclaimer: I don't know much of the development of Fedy and people involved. Just a very thankful user.

**Comment by atonal174** [comment]
This is a joke.

So since cloning and installing from there works, it means fedy is actually working software. It's just not deployed. It just takes a couple of commands to deploy this onto any server.

@sudoforge It seems you're either too busy to spend ~15min it takes to deploy, or your schedule is too sporadic where one day you have time to type lengthy comments saying you'd deploy by the end of the day but then fail to do so on the very same day.

You should relinquish this responsibility to the community, just like you previously accepted this responsibility from somebody else here. Otherwise you're the reason for the death of this project.

P.S. Nothing against you, and I understand you have other responsibilities. It's just not an excuse.

**Comment by wheeler01** [comment]
I am a proud Fedy user. I am thankful the project exists. I admit I miss the days of RPM Fedy. That said, let us not forget, @sudoforge and @danstewart are freely giving of their time to make the lives of Fedora/Fedy users easier. I for one am grateful for what the have done and continue to do. I also hope for continued success of the project. While I'm at it, come on folks, a git clone is not that hard. Really?

**Comment by atonal174** [comment]
@wheeler01 A git clone is not hard at all, and it works! But the same logic goes for building and deploying it. It's less than 5 commands.

Kudos to @sudoforge for working on it so far, but nobody is forcing him to dedicate his free time that he clearly doesn't have, to this project. He accepted the responsibility from someone else here. He was doing a good job, but if he can't do it any longer, he should give it back to the community.

P.S. If making an rpm is too difficult for some reason, make an npm package or a pip package or literally anything that allows users to automatically update fedy, instead of having to manually check fedy's repo for updates.

**Comment by wheeler01** [comment]
I would point out that if you know git clone is not hard and it works (your words) then try being grateful for what has been given to the community, instead of spotlighting what you think is missing, in a manner that not only detracts from the efforts of others and the project but, also makes something into a problem that has a solution which (by your own admission) "is not hard at all, and it works". Just saying, sometimes half-full is a better perspective than half-empty.

**Comment by atonal174** [comment]
@wheeler01 

I am grateful. I said it in my previous comment. 

However I was in too many projects that died for absolutely no reason. Almost all start dying exactly like this, and almost all get "glass half-full" comments like yours e.g. Arc theme died for having its keys expired! Initial forking attempts also failed because people where busy thanking the original developer who went awol.

System software becomes stale quickly. Fedy already doesn't work well enough, not only because updating a repo manually is a pain compared to `dnf upgrade`, but packages themselves have problems e.g. Oracle jdk is the most recent one. 

Problems like these almost never get fixed, if the the software itself is not discoverable. Since Fedy works well enough, it's simply irresponsible of the developers not to deploy it. Again, grateful and all. But it's time to give it up. @sudoforge got it from the original developer. If original developer acted like this, Fedy would have died already.

**Comment by wheeler01** [comment]
I understand and respect your point. My point (which I think is being missed) is that this is a free-of-charge gift the developers have chosen to offer to the community. As a trained software and network engineer, who has done both for quite a while, I have an understanding of what demands any project can have. Also, you are right, I have seen many projects follow the path you described. The fact remains, it is a gift of people's time and talent. A gift,  I for one will gladly use as long as reasonably possible.

**Comment by danstewart** [comment]
@wheeler01 
> Oracle jdk is the most recent one.

Do you mean JRE? If so that's fixed: 923468dcb9bb3fb29ad027a0a4610b8c50a8cfc3
If you do mean JDK could you open an issue describing the problem.

If you have issues with any plugins please raise it as an issue.

---

We understand it's more convenient using `dnf` and having fedy auto update but for the time being I suggest installing from source until we get the workflow sorted.

**Comment by sudoforge** [comment]
For those who have offered to help, or who have suggested that I "relinquish control" (as if I'm barricading others from helping out), feel free to start digging through the issue backlog and contribute patches, comment on old issues, rewrite the gui and cli, refactor the deployment process, set up integration tests, convert plugins to `*.rpm` packages, or contribute in any way that you see fit.

If you are unable to do so, I find it quite humorous that I am chastised for the same.

**Comment by sudoforge** [comment]
That said, the above ref(s) close this issue out. Fedy is now generally available for F30 and F31.

Locking conversation.
